=== xizhong365/myj/myj/target/classes/data/weekly-euc-jp.dtd
<?xml encoding="euc-jp"?>

<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either the GNU
 General Public License Version 2 only ("GPL") or the Common Development
 and Distribution License("CDDL") (collectively, the "License").  You
 may not use this file except in compliance with the License. You can obtain
 a copy of the License at https://glassfish.dev.java.net/public/CDDL+GPL.html
 or glassfish/bootstrap/legal/LICENSE.txt.  See the License for the specific
 language governing permissions and limitations under the License.
 
 When distributing the software, include this License Header Notice in each
 file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
 Sun designates this particular file as subject to the "Classpath" exception
 as provided by Sun in the GPL Version 2 section of the License file that
 accompanied this code.  If applicable, add the following below the License
 Header, with the fields enclosed by brackets [] replaced by your own
 identifying information: "Portions Copyrighted [year]
 [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by only the CDDL or
 only the GPL Version 2, indicate your decision by adding "[Contributor]
 elects to include this software in this distribution under the [CDDL or GPL
 Version 2] license."  If you don't indicate a single choice of license, a
 recipient has the option to distribute your version of this file under
 either the CDDL, the GPL Version 2 or to extend the choice of license to
 its licensees as provided above.  However, if you add GPL Version 2 code
 and therefore, elected the GPL Version 2 license, then the option applies
 only if the new code is made subject to such option by the copyright
 holder.
-->

<!--
*************************************************************************
*                                                                       *
*	DPSD PDG週報用DTD	  weekly.dtd                            *
*                                                                       *
*   Copyright 1997 Fuji Xerox Information Systems Co.,Ltd.              *
*                                                                       *
*************************************************************************
-->


<!-- 変更履歴
    Version 1.0 1997/10/29 作成   村田真
-->

<!ELEMENT 週報                    (年月週, 氏名, 業務報告リスト)>

<!ELEMENT 年月週                  (年度, 月度, 週)>
<!ELEMENT 年度                    (#PCDATA)> <!-- 年度を表す数字 -->
<!ELEMENT 月度                    (#PCDATA)> <!-- 月度を表す数字 -->
<!ELEMENT 週                      (#PCDATA)> <!-- 何週目かを表す数字 -->

<!ELEMENT 氏名                    (氏, 名)>
<!ELEMENT 氏                      (#PCDATA)>
<!ELEMENT 名                      (#PCDATA)>

<!ELEMENT 業務報告リスト          (業務報告+)>
<!ELEMENT 業務報告                (業務名, 業務コード, 工数管理, 
                                   予定項目リスト, 
                                   実施事項リスト, 
                                   上長への要請事項リスト,
                                   問題点対策?)>
<!ELEMENT 業務名                  (#PCDATA)>  <!-- 業務コード一覧を参照 -->
<!ELEMENT 業務コード              (#PCDATA)>  <!-- 業務コード一覧を参照 -->

<!ELEMENT 工数管理                (見積もり工数, 実績工数, 
                                   当月見積もり工数, 当月実績工数)>
<!ELEMENT 見積もり工数            (#PCDATA)>  <!-- 単位は時間 -->
<!ELEMENT 実績工数                (#PCDATA)>  <!-- 単位は時間 -->
<!ELEMENT 当月見積もり工数        (#PCDATA)>  <!-- 単位は時間 -->
<!ELEMENT 当月実績工数            (#PCDATA)>  <!-- 単位は時間 -->

<!ELEMENT 予定項目リスト          (予定項目*)>
<!ELEMENT 予定項目                ((P | OL | UL)+)>
<!ELEMENT 実施事項リスト          (実施事項*)>
<!ELEMENT 実施事項                ((P | OL | UL)+)>
<!ELEMENT 問題点対策              ((P | OL | UL)+)>

<!ELEMENT 上長への要請事項リスト  (上長への要請事項*)>
<!ELEMENT 上長への要請事項        ((P | OL | UL)+)>


<!-- XMLであらかじめ定義された実体 -->
<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;">

<!-- HTMLの汎用的なタグ -->
<!ELEMENT P      (#PCDATA | EM | STRONG | A)*>
<!ELEMENT OL     (LI)*>
<!ELEMENT UL     (LI)*>
<!ELEMENT LI     (#PCDATA | EM | STRONG | A)*>
<!ELEMENT EM     (#PCDATA | EM | STRONG | A)*>
<!ELEMENT STRONG (#PCDATA | EM | STRONG | A)*>
<!ELEMENT A      (#PCDATA | EM | STRONG)*>
<!ATTLIST A
        name    CDATA   #IMPLIED
        href    CDATA   #IMPLIED
        >

=== xizhong365/myj/myj/target/classes/data/weekly-euc-jp.xml
<?xml version="1.0" encoding="euc-jp"?>

<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either the GNU
 General Public License Version 2 only ("GPL") or the Common Development
 and Distribution License("CDDL") (collectively, the "License").  You
 may not use this file except in compliance with the License. You can obtain
 a copy of the License at https://glassfish.dev.java.net/public/CDDL+GPL.html
 or glassfish/bootstrap/legal/LICENSE.txt.  See the License for the specific
 language governing permissions and limitations under the License.
 
 When distributing the software, include this License Header Notice in each
 file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
 Sun designates this particular file as subject to the "Classpath" exception
 as provided by Sun in the GPL Version 2 section of the License file that
 accompanied this code.  If applicable, add the following below the License
 Header, with the fields enclosed by brackets [] replaced by your own
 identifying information: "Portions Copyrighted [year]
 [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by only the CDDL or
 only the GPL Version 2, indicate your decision by adding "[Contributor]
 elects to include this software in this distribution under the [CDDL or GPL
 Version 2] license."  If you don't indicate a single choice of license, a
 recipient has the option to distribute your version of this file under
 either the CDDL, the GPL Version 2 or to extend the choice of license to
 its licensees as provided above.  However, if you add GPL Version 2 code
 and therefore, elected the GPL Version 2 license, then the option applies
 only if the new code is made subject to such option by the copyright
 holder.
-->

<!DOCTYPE 週報 SYSTEM "weekly-euc-jp.dtd">
<!-- 週報サンプル -->
<週報>
  <年月週>
    <年度>1997</年度>
    <月度>1</月度>
    <週>1</週>
  </年月週>

  <氏名>
    <氏>山田</氏>
    <名>太郎</名>
  </氏名>

  <業務報告リスト>
    <業務報告>
      <業務名>XMLエディターの作成</業務名>
      <業務コード>X3355-23</業務コード>
      <工数管理>
        <見積もり工数>1600</見積もり工数>
        <実績工数>320</実績工数>
        <当月見積もり工数>160</当月見積もり工数>
        <当月実績工数>24</当月実績工数>
      </工数管理>
      <予定項目リスト>
        <予定項目>
          <P>XMLエディターの基本仕様の作成</P>
        </予定項目>
      </予定項目リスト>
      <実施事項リスト>
        <実施事項>
          <P>XMLエディターの基本仕様の作成</P>
        </実施事項>
        <実施事項>
          <P>競合他社製品の機能調査</P>
        </実施事項>
      </実施事項リスト>
      <上長への要請事項リスト>
        <上長への要請事項>
          <P>特になし</P>
        </上長への要請事項>
      </上長への要請事項リスト>
      <問題点対策>
        <P>XMLとは何かわからない。</P>
      </問題点対策>
    </業務報告>

    <業務報告>
      <業務名>検索エンジンの開発</業務名>
      <業務コード>S8821-76</業務コード>
      <工数管理>
        <見積もり工数>120</見積もり工数>
        <実績工数>6</実績工数>
        <当月見積もり工数>32</当月見積もり工数>
        <当月実績工数>2</当月実績工数>
      </工数管理>
      <予定項目リスト>
        <予定項目>
          <P><A href="http://www.goo.ne.jp">goo</A>の機能を調べてみる</P>
        </予定項目>
      </予定項目リスト>
      <実施事項リスト>
        <実施事項>
          <P>更に、どういう検索エンジンがあるか調査する</P>
        </実施事項>
      </実施事項リスト>
      <上長への要請事項リスト>
        <上長への要請事項>
          <P>開発をするのはめんどうなので、Yahoo!を買収して下さい。</P>
        </上長への要請事項>
      </上長への要請事項リスト>
      <問題点対策>
        <P>検索エンジンで車を走らせることができない。（要調査）</P>
      </問題点対策>
    </業務報告>
  </業務報告リスト>
</週報>
